#%RAML 1.0 ResourceType
get:
   description: <<get-description>>
   responses:
     200:
       body:
         application/json:
            type: <<get-type>>
            example: <<get-example>>
    